

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      recordExceptions:
        - feign.FeignException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
  instances:
    Weather:
      baseConfig: default


weather:
  apiKey: ${API_KEY}